services:
  web:
    image: library/nginx:alpine
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php

  php:
    image: library/php:7.4-fpm-alpine
    volumes:
      - ./app:/var/www/html